### ISSUE TITLE
Set OpenFaaS image pull policy to IfNotPresent

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ofc-bootstrap#100]
## Expected Behaviour

Images are immutable so never need to be pulled than once, this can just generate additional cold-start latency

## Current Behaviour

Set the OpenFaaS controller image pull policy to `IfNotPresent` rather than `Always`

This option is available via helm: https://github.com/openfaas/faas-netes/tree/master/chart/openfaas#configuration

## Steps to Reproduce (for bugs)

0. Deploy with kind - then check the pull policy of the controller in the openfaas/gateway pod - it will be `Always`
1. Update the scripts which deploy OpenFaaS via helm
2. Deploy with kind - then check the pull policy of the controller in the openfaas/gateway pod - it should now be `IfNotPresent`

## Context

Improving upon any potential cold-start time from idled functions.

**Comment by alexellis** [comment]
@Waterdrips ?

**Comment by Waterdrips** [comment]
Derek assign: me

**Comment by Waterdrips** [comment]
Good spot @alexellis 

I have re-worked this and the image below shows the image_pull_policy env var on the gateway pod set to IfNotPresent. 

![image](https://user-images.githubusercontent.com/40488132/67904132-6c5fd800-fb65-11e9-9d9a-a83d1e17c5e3.png)
