### ISSUE TITLE
Outdated function images

### ISSUE THREAD

**Issue by martindekov** [openfaas-incubator/ofc-bootstrap#105]
Due to functions being unable to be deployed in case missing secrets for GitHub/GitLab we had to add the `stack.yml` from openfaas-cloud. Those images need double update in openfaas-cloud and here in order to be latest versions. Recently new features to openfaas-cloud were added which means we should follow along the stack.yml from openfaas-cloud here.

## Expected Behaviour

Image versions/tags to be latest.

## Current Behaviour

Images tags are outdated aka openfaas-cloud has:
`    image: functions/github-event:0.8.0`
while people who use the bootstrapper have
`    image: functions/github-event:0.7.4`

## Possible Solution

Check out [stack.yml](https://github.com/openfaas/openfaas-cloud/blob/master/stack.yml) from openfaas-cloud repo and replicate the images in the stack.yml [here](https://github.com/openfaas-incubator/ofc-bootstrap/blob/master/templates/stack.yml)

## Steps to Reproduce (for bugs)

N/A

## Context

People are using outdated functions.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
N/A
* Docker version `docker version` (e.g. Docker 17.0.05 ):
N/A
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu
* Link to your project or a code example to reproduce issue:
N/A
* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:
N/A

**Comment by martindekov** [comment]
Derek add label: good first issue, help wanted

**Comment by matipan** [comment]
@martindekov derek is doing the same thing to you. I tried adding labels on a different issue and it did not work. Adding labels on separate comments worked ok though

**Comment by alexellis** [comment]
@marbar3778 @matipan sorry that this is a bit of a moving target. Can we have another go at this and make sure everything is in sync?

**Comment by martindekov** [comment]
I was wondering is there a need for an Issue to stay open like this? Since this is a never ending task. Like we do with the organizations thing (for when someone is using openfaas to add its logo to the site)

**Comment by martindekov** [comment]
Like add tracking label or `Tracking Issue: Outdated function images `

**Comment by alexellis** [comment]
@martindekov when you have time today, please can you check the PR and update any other image versions missing in the stack.yml or gitlab.yml?

**Comment by martindekov** [comment]
Yeah, of course
