### ISSUE TITLE
Add network policies by default

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ofc-bootstrap#111]
## Expected Behaviour

The network policies that control function access to the openfaas ns should be enabled and installed by default, with an option to disable in the init.yaml file.

Network policy PR: https://github.com/openfaas/openfaas-cloud/pull/455

## Possible Solution

Follow the same steps we did for adding the `dockerfile` language or one of the other flags like `scale_to_zero`.

## Similar PR / work

* Add scale_to_zero option to enable scale to zero #103

**Comment by martindekov** [comment]
I suppose I should add another line in [deploy-cloud-components.sh](https://github.com/openfaas-incubator/ofc-bootstrap/blob/master/scripts/deploy-cloud-components.sh) checking if `init.yml` file is enabled if so `kubectl apply -f ./tmp/openfaas-cloud/yaml/network-policy` I hope I got the context right? If so I can go ahead and start it ?

**Comment by alexellis** [comment]
Yes that's basically it as far as I'm concerned 👍
