### ISSUE TITLE
GCP system.{{RootDomain}} DNS not resolving

### ISSUE THREAD

**Issue by chriskolenko** [openfaas-incubator/ofc-bootstrap#116]
I had an issue GCP not resolving system.RootDomain via the *.RootDomain A record. 

I believe this is GCP related issue and I haven't tested else where. 

In the getting started guides it does point people to create an A record for system.{{RootDomain}}. In Kubernetes I'm using external dns, to avoid having to update DNS on changes. This Issue is suggesting a small addition to Ingress to help people like me out. 

I believe this is a good addition to the TLS information too. Wildcard domains are considered a no no in most security circles. IE. Explicitly setting system.{{RootDomain}} inside the TLS hosts.

## Expected Behaviour
*.RootDomain should cover system.RootDomain

## Current Behaviour
system.RootDomain does not resolve using the wildcard

## Possible Solution
Add system.{{RootDomain}} to the ingress

## Steps to Reproduce (for bugs)
Run the bootstrapper on a brand new environment with no DNS setup. Using external dns to manage DNS.

## Context
I hate having to manage my DNS inside a K8 cluster. So letting a tool like External DNS avoids human error. It has great integration with Ingress + Service. 

Personally I also create Certificates for well know domains all the time. system.{{RootDomain}} is one of those. Wildcards always give me a bad impression. <- My Opinion. 

## Your Environment
* FaaS CLI:
```
CLI:
 commit:  25cada08609e00bed526790a6bdd19e49ca9aa63
 version: 0.8.14
```

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```18.09.2```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
```GCP with GKE using K8 1.12```

* Operating System and version (e.g. Linux, Windows, MacOS):
```Linux - Ubuntu 18.04```

* Link to your project or a code example to reproduce issue:
``` N/A ```

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:
``` N/A ```

**Comment by alexellis** [comment]
I'm not sure that I follow the problem.

You don't want to use cert-manager to fetch your TLS certificates using Cloud DNS?
