### ISSUE TITLE
Action Required: Update to cert-manager 0.8.0

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ofc-bootstrap#122]
## Proposed change

Update to cert-manager 0.8.0

Full end to end testing will be required.

Be careful to see all the upgrade notes: https://docs.cert-manager.io/en/latest/tasks/upgrading/upgrading-0.7-0.8.html

## Context

I had an email from LetsEncrypt saying that versions < 0.8.0 will be deprecated and blocked by LetsEncrypt from November.

Here is the web version: https://community.letsencrypt.org/t/blocking-old-cert-manager-versions/98753

## Your Environment

Kubernetes

**Comment by Waterdrips** [comment]
@alexellis is this not required anymore?

**Comment by alexellis** [comment]
It was completed.
