### ISSUE TITLE
Add kubectl during CI to pass validation

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ofc-bootstrap#123]
## Expected Behaviour

CI should pass, but it's breaking due to kubectl not being present on the machine.

## Possible Solution

Add if not present

## Steps to Reproduce (for bugs)

See the build logs using the link on the README.md file

**Comment by arshchimni** [comment]
Would you like to exit out of ci.sh if kubectl is not present? @alexellis

**Comment by alexellis** [comment]
That sounds good.

Please could you send a pull request to add kubectl to the CI machine?

As far as I am aware this is the reason that CI is currently failing

**Comment by Waterdrips** [comment]
@alexellis is this still an issue?

**Comment by alexellis** [comment]
No, I fixed it
