### ISSUE TITLE
[Feature request] Validate Docker registry credentials before proceeding

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ofc-bootstrap#125]
## Expected Behaviour

We can validate that the Docker registry credentials passed by a user, have an entry for the "registry" that they specified in the `init.yaml`

The other thing we can check is that they are not using a `credStore`

## Current Behaviour

User will eventually work it out by troubleshooting error messages. i.e @doowb has this issue.

## Possible Solution

* Create a struct for the Docker config JSON
* Parse it
* Write a unit test for the invalid case
* Write a unit test for the valid case
* Integrate into the main CLI and show evidence of it passing/failing.

https://blog.alexellis.io/golang-writing-unit-tests/

**Comment by alexellis** [comment]
Normally `~/.docker/config.json` - there might be some code in `openfaas/faas-cli` that could help with parsing the file, if we can avoid adding a dependency to Docker it would be better.

**Comment by rajibmitra** [comment]
I am working on this. @alexellis

**Comment by alexellis** [comment]
No problem

**Comment by Waterdrips** [comment]
@rajibmitra - Any updates on this? I got stung by this today (using macos keychain)

**Comment by alexellis** [comment]
@Waterdrips please take this.

We should be able to do this without vendoring code from Docker, just with a simple struct to see if th registry as a value in base64.
