### ISSUE TITLE
ofc-bootstrap -version flag does not show any version information

### ISSUE THREAD

**Issue by doowb** [openfaas-incubator/ofc-bootstrap#130]
## Expected Behaviour

When running `ofc-bootstrap -version` I expect the version of the cli to be printed and the cli to exit.

## Current Behaviour

![image](https://user-images.githubusercontent.com/995160/64437735-d5aaf980-d094-11e9-9f7a-6c8cb824b773.png)

## Possible Solution

I'm not familiar enough with Go or this cli to know if the version is available at runtime, but if it is, then it should just be printed.

## Steps to Reproduce (for bugs)

1. Install `ofc-bootstrap` using the [README.md steps](https://github.com/openfaas-incubator/ofc-bootstrap/#get-ofc-bootstrap)
2.Run `ofc-bootstrap -version`

## Context

I discovered this when @alexellis posted that a new version was available and I wanted to see which version I had since I had just downloaded it a few hours ago. I'm not sure how to see in the repository source which version I have locally so I thought using the cli would be my only option.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
`macOS Sierra 10.12.6`

**Comment by alexellis** [comment]
Thanks for logging this.
