### ISSUE TITLE
Having a dash character '-' in CUSTOMERS repository causes unauthorized error

### ISSUE THREAD

**Issue by michaelkacher** [openfaas-incubator/ofc-bootstrap#132]
I originally had tried leveraging ofc-bootstrap pointing to the following CUSTOMERS file in the init.yml: https://raw.githubusercontent.com/golanghouston/of-test/master/CUSTOMERS

When I would log in to http://system.example.com/dashboard/<username>it properly redirects to github for authorization and when it redirects back to OpenFaaS Cloud you would receive an unauthorized.  This was resolved by creating a repository with no slash in the name: https://raw.githubusercontent.com/michaelkacher/ofccustomers/master/CUSTOMERS

## Expected Behaviour

You should be able to create a repository for the CUSTOMERS file that has a '-' in the name.

## Current Behaviour

The user receives a 401.  In the logs created from running `kubectl logs -n openfaas deploy/edge-auth` you see the following:
```
2019/10/04 17:00:25 Fetching customers from https://raw.githubusercontent.com/golanghouston/of-test/master/CUSTOMERS
2019/10/04 17:00:25 user [michaelkacher] was not a valid customer
```
This occurs when the user does exist in the CUSTOMERS file.  When it you use a repository without the dash the logs will show:
```
2019/10/04 17:15:50 Cookie verified: 0.135889s [200]
```

## Steps to Reproduce (for bugs)

1. Create a new public Github repository
2. Replace the CDN link to CUSTOMERS file in the repository in the customers_url in the init.yaml
3. Run $ ofc-bootstrap -yaml init.yaml
4. Try to log in

## Context

There is an easy work-around. Low impact.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
19.03.2
* Kubernetes version `kubectl version`:
1.15.1

* Are you using faas-netes or the Operator?

* Operating System and version (e.g. Linux, Windows, MacOS):
Windows WSL (tested on WSL 1 and WSL 2)

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:
from logs:
```
2019/10/04 16:55:10 Fetching customers from https://raw.githubusercontent.com/golanghouston/of-test/master/CUSTOMERS
2019/10/04 16:55:11 Using port: 8080
2019/10/04 17:00:20 Cookie verified: 0.000001s [511]
2019/10/04 17:00:20 No cookie or an invalid cookie was found.
2019/10/04 17:00:20 Validate /function/system-dashboard/michaelkacher/ => 307
2019/10/04 17:00:24 OAuth 2 - "/oauth2/authorized"
2019/10/04 17:00:24 Exchange: a148befb3f1aa0b6ee16, for an access_token
2019/10/04 17:00:24 Posting to https://github.com/login/oauth/access_token?client_id=e7ee0eae248b0e619549&client_secret=<mysecretremoved>&code=a148befb3f1aa0b6ee16&state=1570208420
2019/10/04 17:00:24 SetCookie done, redirect to: map[r:[http://system.kcode.dev/dashboard/michaelkacher/] code:[a148befb3f1aa0b6ee16] state:[1570208420]]
2019/10/04 17:00:24 Found redirect value "r"=http://system.kcode.dev/dashboard/michaelkacher/, instructing client to redirect
2019/10/04 17:00:25 CUSTOMERS cache expires in: -14.075333s
2019/10/04 17:00:25 Fetching customers from https://raw.githubusercontent.com/golanghouston/of-test/master/CUSTOMERS
2019/10/04 17:00:25 user [michaelkacher] was not a valid customer
2019/10/04 17:00:25 Cookie verified: 0.137149s [401]
2019/10/04 17:00:25 A valid cookie was not found.
```

**Comment by alexellis** [comment]
This was found to be a red herring / false error.
