### ISSUE TITLE
Replace use of $GOOS-$GOARCH with `uname`

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ofc-bootstrap#134]
## Expected Behaviour

Replace use of `$GOOS` / `$GOARCH` with `uname` so that users do not need to install Golang to run the binary tool.

## Current Behaviour

GOOS / GOARCH are currently used by the SealedSecrets step to export the public key.

## Possible Solution

Construct an equivalent string using one of the `uname` options shown on `uname --help`

https://github.com/openfaas-incubator/ofc-bootstrap/blob/4d88e7e68f6d9d42a5b9711326ab6c5351e27ae6/scripts/export-sealed-secret-pubcert.sh

**Comment by sterchelen** [comment]
@alexellis I would like to take in charge this issue.

**Comment by alexellis** [comment]
Closed via #137 

Please add "Closes: #ISSUE" into your next PR :-)

Thank you

Released in: https://github.com/openfaas-incubator/ofc-bootstrap/releases/tag/0.7.5
