### ISSUE TITLE
Update to cert-manager 0.11.0 from 0.10.0

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ofc-bootstrap#138]
## Expected Behaviour

I would like cert-manager 0.11.0 to work out of the box

## Current Behaviour

We are pinning to 0.10.0

## Possible Solution

There are some breaking changes with annotations and potentially other areas that need addressing.

https://docs.cert-manager.io/en/release-0.11/

See [Upgrading from v0.10 to v0.11](https://docs.cert-manager.io/en/release-0.11/tasks/upgrading/upgrading-0.10-0.11.html)

**Comment by alexellis** [comment]
References I could find with a quick search:

https://github.com/openfaas-incubator/ofc-bootstrap/blob/master/pkg/tls/tls.go

https://github.com/openfaas-incubator/ofc-bootstrap/blob/master/templates/issue-prod.yml

https://github.com/openfaas-incubator/ofc-bootstrap/blob/master/templates/k8s/ingress-auth.yml

https://github.com/openfaas-incubator/ofc-bootstrap/blob/master/templates/k8s/ingress-wildcard.yml

https://github.com/openfaas-incubator/ofc-bootstrap/tree/master/templates/k8s/tls

**Comment by Waterdrips** [comment]
Ill start to work through this.

**Comment by alexellis** [comment]
Thank you
