### ISSUE TITLE
Proposal: Add registry login command to ofc-bootstrap

### ISSUE THREAD

**Issue by Waterdrips** [openfaas-incubator/ofc-bootstrap#152]
It would be great to be able to provide a command to create the config.json registry secret file using ofc-bootstrap. Some users have the secrets helper installed by default with docker and the login command stores the secrets outside of the file.

## Expected Behaviour

A user should be able to run `ofc-bootstrap --registry-login` with `--username` `--password-stdin` (or `--password`) and optionally `--url` to generate the registry config file in ./tmp/config.json (create if not exists)

## Current Behaviour

No checks (pending #125 where there is a check being added) on the file at the moment, so if a user has incorrectly setup the file then the deployment happens, creates a bad secret, and then cant pull any functions. 

## Possible Solution

implement a `--registry-login` command that creates a valid file in ./tmp/config.json for the supplied url (or docker's default `https://index.docker.io/v1/`  if no url provided)

**Comment by alexellis** [comment]
I think it would be a sub-command `docker-login` or `registry-login` or `generate registry-login`

Then the server ARG would be needed and like you say `--username`. I think only having `--password-stdin` is fine.

Output file should perhaps be in the same folder by default? Not sure.

**Comment by alexellis** [comment]
Please go ahead with this. It doesn't actually have to validate the user's password, just generate a base64-encoded Docker config json file.

Another thought is what we can do for AWS ECR users, we could just take different flags for them perhaps and generate the equivalent file.

**Comment by LucasRoesler** [comment]
This is a good idea, this part definitely slowed me down when I was trying the bootstrap.  I think it might actually be ok to have a dedicated subfolder for credentials and other custom fields.  We can easily ignore the whole folder and be certain it is never committed to a repo

**Comment by alexellis** [comment]
@csakshaug has some ideas about secret management too

**Comment by Waterdrips** [comment]
derek assign: me

**Comment by Waterdrips** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Also `/` can take the place of the text `Derek`
