### ISSUE TITLE
ECR registration dont respect the "registry" region

### ISSUE THREAD

**Issue by csakshaug** [openfaas-incubator/ofc-bootstrap#155]
The `register_image` function is using today a `registry_url` to register the new ECR register, the `register_url`  have  `aws account id`, `region` as part of the URL. The problem is that even if you have a region inside the URL the function will not use it. It uses it an environment variable `AWS_DEFAULT_REGION` that has a default value [eu-central-1](https://github.com/openfaas/openfaas-cloud/blob/master/aws.yml#L21), but there is no easy way to overrides that in today's `init.yaml` file.

## Expected Behaviour
That `register_image` should respect the region defined in the `registry`

## Current Behaviour
It uses [`AWS_DEFAULT_REGION`](https://github.com/openfaas/openfaas-cloud/blob/master/register-image/handler.go#L60)

## Possible Solution

There are at least two solutions here

Extract the `region` from `registry`  and use that instead if env are not set. Remove the default value from [aws.yaml](https://github.com/openfaas/openfaas-cloud/blob/master/aws.yml#L21)
Or/And add support to override the [`AWS_DEFAULT_REGION`](https://github.com/openfaas/openfaas-cloud/blob/master/register-image/handler.go#L60) in the `init.yaml` file

**Comment by alexellis** [comment]
Would you like to work on this?

**Comment by csakshaug** [comment]
Yes I could

**Comment by alexellis** [comment]
@Waterdrips is this still an issue?

**Comment by Waterdrips** [comment]
looks like it:
https://github.com/openfaas/openfaas-cloud/blob/54b9ff24257792fc8c555d5b61ad1e8b294220fc/register-image/handler.go#L57

This line (above) grabs the env var which we dont have a way of overriding for ofc-bootstrap.

we could add this as an option in init.yaml and then create a templated aws.yml that overrides it?

**Comment by Waterdrips** [comment]
@csakshaug can I work on this or did you have a solution on the way?
