### ISSUE TITLE
Secrets not created when values are multiple words.

### ISSUE THREAD

**Issue by doowb** [openfaas-incubator/ofc-bootstrap#16]
I entered a sentence for the value in my `github-webhook-secret` in the [init.yml](./init.yml) file, but when the functions were deploying, they gave an error because they couldn't find they secret. In the output, there is an error when the secret is being created saying "error: exactly one NAME is required, got 7".

I'm not as familiar with go (as I am with JavaScript), but I quoted the value in [pkg/types/secrets](./pkg/types/secrets.go) and it still gave the error. The command looked like it would be correct.

## Expected Behaviour

Secrets should be allowed to contain spaces.

## Current Behaviour

Error when creating secrets: "error: exactly one NAME is required, got 7".

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  70ebebb71f015f4edb0c3e1f03ef3d262b1d84f6
 version: 0.7.7
```
* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Started a Kubernetes cluster through Kind backed by Docker.

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
https://github.com/openfaas-incubator/ofc-bootstrap/blob/master/pkg/types/secrets.go

We should just use Command for the base command i.e. `kubectl` and pass everything else via `Args`
