### ISSUE TITLE
Enable multiple YAML files for "apply"

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ofc-bootstrap#163]
Enable multiple YAML files for "apply"

## Expected Behaviour

As inspired by Kustomize, helm and an experimental app by @csakshaug, we should allow users to provide > 1 file for `apply`:

```sh
ofc-bootstrap apply --file example.init.yaml --file production.yaml
```

The files will be merged, this means that `production.yaml` only needs overrides adding such as the domain name or registry address, and everything else is taken from upstream. It also means if changes are made in example.init.yaml, `production.yaml` doesn't need to be kept in sync.
 
## Current Behaviour

Manual merging between releases and updates of example.init.yaml

## Possible Solution

Use https://github.com/imdario/mergo which is also used by moby, Kubernetes and other well-known projects.

**Comment by alexellis** [comment]
Dependent on merge of: https://github.com/openfaas-incubator/ofc-bootstrap/pull/162

**Comment by alexellis** [comment]
162 was merged, this can be worked on now.

**Comment by Waterdrips** [comment]
Isn't this completed?

**Comment by alexellis** [comment]
Yes
