### ISSUE TITLE
registry-login command should read password from stdin

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ofc-bootstrap#169]
## Expected Behaviour

registry-login command should read password from stdin, so that the password is not kept in bash logs / historyh

## Current Behaviour

Only `--password` is available, despite `--password-stdin` being referenced in the command help message.

**Comment by Waterdrips** [comment]
I will look at this when I next get a few mins. In the meantime if you put a space before the command it wont be saved to history
