### ISSUE TITLE
Install our own version of helm3

### ISSUE THREAD

**Issue by Waterdrips** [openfaas-incubator/ofc-bootstrap#180]
## Expected Behaviour

Download and use our own helm / helm3 version.

## Current Behaviour

We rely on it being preinstalled.

## Possible Solution

vendor the code in k3sup that downloads helm.
https://github.com/alexellis/k3sup/blob/master/cmd/apps/kubernetes_exec.go

**Comment by alexellis** [comment]
We covered this in our pair-programming session
