### ISSUE TITLE
Merging overides with base settings for lists (slices)

### ISSUE THREAD

**Issue by Waterdrips** [openfaas-incubator/ofc-bootstrap#185]
## Expected Behaviour

We should be able to provide a single override in an override file that either appends to, or replaces a secret. for example we could set the default location for the docker registry config file to /tmp/dockerconfig.json.

We expect that setting this single override will change the base config's secrets to have this.

 
## Current Behaviour

We currently see the base config secrets totally removed and replaced with the overide.
## Possible Solution

do a custom merge of slices, where we append if the new item doesn't exist and we replace if we find the value in the slice.

## Context

providing an override secret replaces all secrets, it doesn't add or replace an existing secret.

**Comment by alexellis** [comment]
Fixed with custom code, for the secrets slice only.
