### ISSUE TITLE
key and key.pub re-generated every time (even if exist)

### ISSUE THREAD

**Issue by Waterdrips** [openfaas-incubator/ofc-bootstrap#198]
The JWT private and public keys (key.pub and key) get re-generated every run, 

I think this is because the are set as `value_command: "openssl ecparam -genkey -name prime256v1 -noout -out ./tmp/key"` 

using value_command re-generates every time regardless of if they exist. 

I could change them to be value_from after generation, or generating them myself, but the default re-generates every rum of ofc-bootstrap.

## Expected Behaviour

re-running doesn't change the secret values.

I may want to use an init.yaml and set of secrets as a disaster recovery (DR) strategy.
This makes it more difficult, or could lead to confusion.
## Current Behaviour

the key and key.pub are re-generated even if they exist.

## Possible Solution

We could make the command check to see if that file exists before re-creating? 

## Steps to Reproduce (for bugs)

1. run ofc-bootstrap, note down key and key.pub values
2.re run the ofc-bootstrap command
3. check the key and key.pub values, they will be different from before

## Context

Planning for DR, this could cause issues if a user doesn't know that these will be different.

**Comment by alexellis** [comment]
Suggestion from call with @Waterdrips - run `os.Stat` on the file before creating, if it exists, don't regenerate.
