### ISSUE TITLE
Question: Multiple Private Registry

### ISSUE THREAD

**Issue by okhiroyuki** [openfaas-incubator/ofc-bootstrap#204]
## Expected Behaviour

We want to support multiple private registries in the OpenFaaS cloud, just like OpenFaaS.
I would like to know the specific method.

## Current Behaviour

I actually ran OpenFaaS on Azure and tried to get it to work with multiple Private Repository registrations.
As for OpenFaaS Cloud, I've only read the [USER_GUIDE](https://github.com/openfaas-incubator/ofc-bootstrap/blob/master/USER_GUIDE.md).

**Comment by Waterdrips** [comment]
Hi @okhiroyuki, apologies about taking so long to get back to you.

What's the usecase for multiple private registries for OpenFaaS Cloud? 

Currently the core components build and push the images up to a registry and this same one is used to pull and run the functions. How would you see multiple private registries working for OFC, is this for part of a build on the `dockerfile` lang?

**Comment by okhiroyuki** [comment]
Hi @Waterdrips , Thank you for your reply.

I thought the expected behavior would be for the user to be able to specify their own registry, but this was a question I was asking without knowing how openfaas cloud works.
This issue can be closed and is fine.

**Comment by Waterdrips** [comment]
Thanks @okhiroyuki - happy to take any feedback on openffas cloud, the installer and anything that could be improved. 

If your not on the OpenFaaS slack it would be great to see you join.
