### ISSUE TITLE
create-github-app failing

### ISSUE THREAD

**Issue by Waterdrips** [openfaas-incubator/ofc-bootstrap#210]
./ofc-bootstrap create-github-app --root-domain ofc.example.com --name ofc1-example-com

This creates the page, then on submit im not getting a github app details filled in.

## Expected Behaviour
Github App created with values

## Current Behaviour
Im getting blank fields in the github app when submitting from our page.

## Possible Solution

I wonder if the API has changed github's side or we have introduced an issue.

## Steps to Reproduce (for bugs)

1. build from master branch
2. ofc-bootstrap create-github-app --root-domain ofc.heyal.uk --name ofc1-heyal-uk 

## Your Environment

* `faas-cli version` ( full output ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Kubernetes version `kubectl version`:

* Are you using faas-netes or the Operator?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by austinrivas** [comment]
I am also experiencing this issue

OS: Ubuntu 18
Docker: 19
Kubectl: 1.18

**Comment by alexellis** [comment]
I know that you changed this code recently Alistair, can you take point on this if it's broken and find out either way what the solution is?

**Comment by alexellis** [comment]
@Waterdrips

**Comment by Waterdrips** [comment]
@alexellis it looks like github have removed the ability to create apps using the API. 

https://developer.github.com/v3/apps/ has no reference to the url we were using `https://github.com/settings/apps/new`

**Comment by alexellis** [comment]
https://developer.github.com/v3/apps/#create-a-github-app-from-a-manifest

**Comment by Waterdrips** [comment]
oh yeah, DOH!

So it looks like I'm being redirected through `/login` before being sent back to `apps/new` and we loose the manifest=<json string> parameter. Therefore nothing is filled in on the app.

![image](https://user-images.githubusercontent.com/40488132/83451430-d79cc000-a44e-11ea-9ed9-3f57b3e73d80.png)

**Comment by Waterdrips** [comment]
Iv opened a support ticket with github.

**Comment by Waterdrips** [comment]
Github have confirmed there is an issue here and raised a ticket for their engineering team to look into.

They said they don't have a timescale at the moment but would contact me when they have more info.

**Comment by Waterdrips** [comment]
/close

This has been confirmed FIXED by github :tada:
