### ISSUE TITLE
Is ofc-bootstrap works with hosted Gitlab.com?

### ISSUE THREAD

**Issue by kpiyush17** [openfaas-incubator/ofc-bootstrap#217]
Hi,

We use hosted Gitlab to store our function codes. I saw the blog posts and docs on how the ofc-bootstrap integrates with self-hosted GitLab. I want to know if it will work for Gitlab.com and if yes, what changes need to be done in init.yaml file.

Thanks

**Comment by alexellis** [comment]
No, sorry. Unlike GitHub.com, GitLab.com doesn't provide suitable APIs for integration. The closest thing I found last time someone asked (we keep checking periodically), was project-level webhooks, which require users to pay.

Assuming this is for personal use, then for the few functions you may have, perhaps you could use GitHub.com and sync with GitLab, or run a small self-hosted instance replicated from GitLab.com?

We would be open to a discussion about a consulting project, if a customer needed this.
