### ISSUE TITLE
Update OFC Authorization code to avoid depreciation of GitHub API calls

### ISSUE THREAD

**Issue by Waterdrips** [openfaas-incubator/ofc-bootstrap#219]
https://github.com/openfaas/openfaas-cloud/pull/664

We need to bump OFC version once the above is merged and released so our Github users don't install a version with deprecated GitHub Authorization API calls

## Expected Behaviour

use the above version
## Current Behaviour

current version will stop working on 1st Oct

**Comment by besirkurtulmus** [comment]
When I try to create a new installation, it seems that I'm getting an empty token from the github auth server.

I'm wondering if anyone else is having this issue?

**Comment by wilsonianb** [comment]
I think an updated [`github-status`](https://hub.docker.com/r/functions/github-status/tags) Docker image needs to pushed with the changes that resolve this issue (https://github.com/openfaas/openfaas-cloud/pull/664).

**Comment by alexellis** [comment]
@besirkurtulmus this is the first time we've heard from you. Glad you are finding OpenFaaS Cloud useful, what are you doing with it?

**Comment by alexellis** [comment]
/set title: Update OFC Authorization code to avoid depreciation of GitHub API calls

**Comment by besirkurtulmus** [comment]
> @besirkurtulmus this is the first time we've heard from you. Glad you are finding OpenFaaS Cloud useful, what are you doing with it?

Trying to use it for audio processing. Got the basic installation working, but still trying to get the cloud version working.

Do you have a timeline for updating the `github-status` image/function?

**Comment by Waterdrips** [comment]
/close

this is done
