### ISSUE TITLE
Template namespaces

### ISSUE THREAD

**Issue by doowb** [openfaas-incubator/ofc-bootstrap#25]
## Expected Behaviour

Allow users to specify the `openfaas` (system-namespace?) and `openfaas-fn` (function-namespace?) namespaces.

I'm not sure what the wider impact this has (e.g. `openfaas` helm deployment, services that aren't using the common templates, etc...)

**Comment by alexellis** [comment]
Derek close: inactive

**Comment by alexellis** [comment]
@matipan @zeerorg @martindekov  should we revisit, or wait for user-demand?

**Comment by martindekov** [comment]
I think this is a great Idea, It will be fairly easy implementation I think ATM though I can't take this as I am overcrowded with the university. I see how this will be implemented I think it will be perfect for new contributors I can give guidelines.

**Comment by matipan** [comment]
I think it's a good idea to have this implemented. This aligns well with the work that would be done here on #104
