### ISSUE TITLE
Backport Kubernetes changes to openfaas-cloud

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ofc-bootstrap#26]
## Expected Behaviour

We should backport the templated Kubernetes changes to openfaas-cloud and look to create a small helm chart for it. This means we can concentrate on the files which are common between Swarm / K8s.

## Current Behaviour

They'll have to be maintained separately

**Comment by alexellis** [comment]
Related - https://github.com/openfaas/openfaas-cloud/issues/363

**Comment by Waterdrips** [comment]
/close

this this is covered with openfaas chart, and the openfaas cloud WIP chart
