### ISSUE TITLE
Provide update scripts

### ISSUE THREAD

**Issue by ivanayov** [openfaas-incubator/ofc-bootstrap#29]
The way we currently use the tool to deploy OpenFaaS Cloud is by pre-reseting the cluster, as it requires a clean environment.
If this is used in production, people may want to be able to update the cloud to latest version or edit their configuration, without loosing their functions.

## Expected Behaviour

Provide a way to update the cluster if configuration is edited and/or there is a new version of OpenFaaS Cloud.

## Current Behaviour

Running ofc-bootstrap requires clean cluster.

**Comment by alexellis** [comment]
Derek close: nice-to-have

**Comment by alexellis** [comment]
Let's track this through the status / roadmap in the README.
