### ISSUE TITLE
Update cert-manager to v0.6.0

### ISSUE THREAD

**Issue by ivanayov** [openfaas-incubator/ofc-bootstrap#35]
It's not available in helm/charts, as blocked by  [#10830](https://github.com/helm/charts/pull/10830) and [#90](https://github.com/helm/chart-testing/pull/90)

Once it's in the repo, update `install-cert-manager.sh` to use `v0.6.0` and test in all existing DNS Services (GC DNS and Route53) with enabled TLS.

The version is currently available in `jetstack` chart repo
```
helm repo add jetstack https://charts.jetstack.io/
helm repo update
helm install \
    --name cert-manager \
    --namespace kube-system \
    --version v0.6.0 \
    jetstack/cert-manager
```

Follow up of #28

Needs extra annotation if installed into an existing namespace (as in our case it's in `kube-system`):
```
kubectl label namespace kube-system certmanager.k8s.io/disable-validation=true
```
https://cert-manager.readthedocs.io/en/latest/admin/resource-validation-webhook.html#tls-configuration

**Comment by alexellis** [comment]
Derek close: Fixed and released.
