### ISSUE TITLE
How to update templates easily from OpenFaaS Cloud?

### ISSUE THREAD

**Issue by ivanayov** [openfaas-incubator/ofc-bootstrap#47]
At the moment every change in the cloud, that's going to templated `yaml` config file, means manually editing existing templates, as well as regularly checking for changes in the `openfaas-cloud` repo.

This issue is for suggestion how to resolve that problem.

First option that comes to mind is fully templating OFC, like here, containing all templates in a separate folder, and  changing code to just do checkout.

**Comment by alexellis** [comment]
Duplicate of #26
