### ISSUE TITLE
Non-generated template referenced when auth is disabled

### ISSUE THREAD

**Issue by M-nana** [openfaas-incubator/ofc-bootstrap#50]
## Current Behaviour
2019/01/25 14:56:44 Validating tools available in PATH
exec:  kubectl version --client
res: Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:16:58Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}

exec:  openssl version
res: LibreSSL 2.2.7

exec:  helm version -c
res: Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}

exec:  faas-cli version
res:   ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  a141dedf94ffeed84412365fd591bdc8999c5a1b
 version: 0.8.3

Plan loaded from: init.yaml
{kubernetes [{s3-secret-key [{s3-secret-key }] openfaas-fn []} {s3-access-key [{s3-access-key }] openfaas-fn []} {basic-auth [{basic-auth-user admin} {basic-auth-password }] openfaas []} {payload-secret [{payload-secret }] openfaas []} {jwt-private-key [] openfaas [{key ./tmp/key openssl ecparam -genkey -name prime256v1 -noout -out ./tmp/key}]} {jwt-public-key [] openfaas [{key.pub ./tmp/key.pub openssl ec -in ./tmp/key -pubout -out ./tmp/key.pub}]} {github-webhook-secret [{github-webhook-secret secret}] openfaas-fn []} {private-key [] openfaas-fn [{private-key ~/Downloads/openfaascloudtest-example.2019-01-25.private-key.pem }]} {of-client-secret [{of-client-secret fb58e886977efbece9cd77452be27e9}] openfaas []} {route53-credentials-secret [] kube-system [{secret-access-key ~/Downloads/openfaascloudtest-example.2019-01-25.private-key.pem }]} {registry-secret [] openfaas [{config.json ~/.docker/config.json }]}] stag.o6s.io docker.io/ofctest/ https://raw.githubusercontent.com/openfaas/openfaas-cloud/master/CUSTOMERS {24253 } false {914f3fb036ce9cd774} {cloud-minio.openfaas.svc.cluster.local:9000 us-east-1 false pipeline} false {email@domain route53  prod us-east-1 ASYAKIUJE8AYRQQ7DU3M}}
Orchestration: Kubernetes
2019/01/25 14:56:45 Creating namespaces
exec:  scripts/create-namespaces.sh
res: namespace/openfaas unchanged
namespace/openfaas-fn unchanged

2019/01/25 14:56:46 namespace/openfaas unchanged
namespace/openfaas-fn unchanged

2019/01/25 14:56:46 
Building Ingress
2019/01/25 14:56:46 Creating Tiller
exec:  scripts/create-tiller-sa.sh
res: serviceaccount/tiller created
clusterrolebinding.rbac.authorization.k8s.io/tiller created

2019/01/25 14:56:46 serviceaccount/tiller created
clusterrolebinding.rbac.authorization.k8s.io/tiller created

2019/01/25 14:56:46 
exec:  scripts/create-tiller.sh
res: Creating /Users/ymeng/.helm 
Creating /Users/ymeng/.helm/repository 
Creating /Users/ymeng/.helm/repository/cache 
Creating /Users/ymeng/.helm/repository/local 
Creating /Users/ymeng/.helm/plugins 
Creating /Users/ymeng/.helm/starters 
Creating /Users/ymeng/.helm/cache/archive 
Creating /Users/ymeng/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /Users/ymeng/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
Happy Helming!

2019/01/25 14:56:46 Creating /Users/ymeng/.helm 
Creating /Users/ymeng/.helm/repository 
Creating /Users/ymeng/.helm/repository/cache 
Creating /Users/ymeng/.helm/repository/local 
Creating /Users/ymeng/.helm/plugins 
Creating /Users/ymeng/.helm/starters 
Creating /Users/ymeng/.helm/cache/archive 
Creating /Users/ymeng/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /Users/ymeng/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
Happy Helming!

2019/01/25 14:56:46 
2019/01/25 14:56:46 Is tiller ready? 1/260
exec:  ./scripts/get-tiller.sh
res: 
tiller 0   <nil>
2019/01/25 14:56:48 Is tiller ready? 2/260
exec:  ./scripts/get-tiller.sh
res: 
tiller 0   <nil>
2019/01/25 14:56:51 Is tiller ready? 3/260
exec:  ./scripts/get-tiller.sh
res: 
tiller 0   <nil>
2019/01/25 14:56:53 Is tiller ready? 4/260
exec:  ./scripts/get-tiller.sh
res: 
tiller 0   <nil>
2019/01/25 14:56:55 Is tiller ready? 5/260
exec:  ./scripts/get-tiller.sh
res: 
tiller 0   <nil>
2019/01/25 14:56:57 Is tiller ready? 6/260
exec:  ./scripts/get-tiller.sh
res: 
tiller 0   <nil>
2019/01/25 14:56:59 Is tiller ready? 7/260
exec:  ./scripts/get-tiller.sh
res: 1
tiller 0 1  <nil>
2019/01/25 14:57:00 Creating Ingress Controller
exec:  scripts/install-nginx.sh
res: 
2019/01/25 14:57:00 
2019/01/25 14:57:00 Error: failed to download "stable/nginx-ingress" (hint: running `helm repo update` may help)

[{s3-secret-key [{s3-secret-key }] openfaas-fn []} {s3-access-key [{s3-access-key }] openfaas-fn []} {basic-auth [{basic-auth-user admin} {basic-auth-password }] openfaas []} {payload-secret [{payload-secret }] openfaas []} {jwt-private-key [] openfaas [{key ./tmp/key openssl ecparam -genkey -name prime256v1 -noout -out ./tmp/key}]} {jwt-public-key [] openfaas [{key.pub ./tmp/key.pub openssl ec -in ./tmp/key -pubout -out ./tmp/key.pub}]} {github-webhook-secret [{github-webhook-secret secret}] openfaas-fn []} {private-key [] openfaas-fn [{private-key ~/Downloads/openfaascloudtest-example.2019-01-25.private-key.pem }]} {of-client-secret [{of-client-secret fb58e886977efbece9cd77452be27e9}] openfaas []} {route53-credentials-secret [] kube-system [{secret-access-key ~/Downloads/openfaascloudtest-example.2019-01-25.private-key.pem }]} {registry-secret [] openfaas [{config.json ~/.docker/config.json }]}]
exec:  scripts/generate-sha.sh
res: 88c5b508aa948ad0a98bbe41beda975617dbb20a
exec:  kubectl create secret generic -n openfaas-fn s3-secret-key --from-literal=s3-secret-key=b0bbfac932eaefe8140065ba2fbbc50c7b2053803b6873b2975c1a88133e0ec2
res: secret/s3-secret-key created

{secret/s3-secret-key created
  0}
exec:  scripts/generate-sha.sh
res: 8a3f2a2b80bcacbb9cfb2009d4969c50e356daff
exec:  kubectl create secret generic -n openfaas-fn s3-access-key --from-literal=s3-access-key=624e104bc5d133bd8e5d13c53718cd6695ec8fdcdfad5078e390413e9fc16a60
res: secret/s3-access-key created

{secret/s3-access-key created
  0}
exec:  scripts/generate-sha.sh
res: b0a444eade65da6e87927c799e983b6abcf78907
exec:  kubectl create secret generic -n openfaas basic-auth --from-literal=basic-auth-user=admin --from-literal=basic-auth-password=6f3db25f694a3fd11a843cbed04ea2d69569812febec65b76b5c1aabd660b9b9
res: secret/basic-auth created

{secret/basic-auth created
  0}
exec:  scripts/generate-sha.sh
res: 8019f5585faeba00301c8c02482ce0935d054e22
exec:  kubectl create secret generic -n openfaas payload-secret --from-literal=payload-secret=8328c3334a07d524f2395ece87fe211cebb250b80e78085fd6972822f725290f
res: secret/payload-secret created

{secret/payload-secret created
  0}
exec:  openssl ecparam -genkey -name prime256v1 -noout -out ./tmp/key
res: 
exec:  kubectl create secret generic -n openfaas jwt-private-key --from-file=key=./tmp/key
res: secret/jwt-private-key created

{secret/jwt-private-key created
  0}
exec:  openssl ec -in ./tmp/key -pubout -out ./tmp/key.pub
res: 
exec:  kubectl create secret generic -n openfaas jwt-public-key --from-file=key.pub=./tmp/key.pub
res: secret/jwt-public-key created

{secret/jwt-public-key created
  0}
exec:  kubectl create secret generic -n openfaas-fn github-webhook-secret --from-literal=github-webhook-secret=secret
res: secret/github-webhook-secret created

{secret/github-webhook-secret created
  0}
exec:  kubectl create secret generic -n openfaas-fn private-key --from-file=private-key=/Users/ymeng/Downloads/openfaascloudtest-example.2019-01-25.private-key.pem
res: secret/private-key created

{secret/private-key created
  0}
exec:  kubectl create secret generic -n openfaas of-client-secret --from-literal=of-client-secret=fb58e886977efbece9cd77452be27e9
res: secret/of-client-secret created

{secret/of-client-secret created
  0}
exec:  kubectl create secret generic -n kube-system route53-credentials-secret --from-file=secret-access-key=/Users/ymeng/Downloads/openfaascloudtest-example.2019-01-25.private-key.pem
res: secret/route53-credentials-secret created

{secret/route53-credentials-secret created
  0}
exec:  kubectl create secret generic -n openfaas registry-secret --from-file=config.json=/Users/ymeng/.docker/config.json
res: secret/registry-secret created

{secret/registry-secret created
  0}
2019/01/25 14:57:02 Creating Minio
exec:  scripts/install-minio.sh
res: 
2019/01/25 14:57:03 
2019/01/25 14:57:03 Error: failed to download "stable/minio" (hint: running `helm repo update` may help)

2019/01/25 14:57:03 Creating Cert-Manager
exec:  scripts/install-cert-manager.sh
res: 
2019/01/25 14:57:03 
2019/01/25 14:57:03 Error: failed to download "stable/cert-manager" (hint: running `helm repo update` may help)

2019/01/25 14:57:03 Creating secrets for functions to consume
exec:  scripts/create-functions-auth.sh
res: secret/basic-auth-user created
secret/basic-auth-password created

2019/01/25 14:57:04 secret/basic-auth-user created
secret/basic-auth-password created

2019/01/25 14:57:04 
2019/01/25 14:57:04 Creating OpenFaaS
exec:  scripts/install-openfaas.sh
res: "openfaas" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "openfaas" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
Release "openfaas" does not exist. Installing it now.

2019/01/25 14:57:07 "openfaas" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "openfaas" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
Release "openfaas" does not exist. Installing it now.

2019/01/25 14:57:07 Error: release openfaas failed: configmaps "alertmanager-config" already exists

exec:  kubectl apply -f tmp/generated-ingress-ingress-wildcard.yaml
res: ingress.extensions/openfaas-ingress created

2019/01/25 14:57:08 ingress.extensions/openfaas-ingress created

exec:  kubectl apply -f tmp/generated-ingress-ingress.yaml
res: ingress.extensions/openfaas-auth-ingress created

2019/01/25 14:57:08 ingress.extensions/openfaas-auth-ingress created

Creating stack.yml
2019/01/25 14:57:08 Creating SealedSecrets
exec:  scripts/install-sealedsecrets.sh
res: SealedSecrets release: v0.7.0
customresourcedefinition.apiextensions.k8s.io/sealedsecrets.bitnami.com created
serviceaccount/sealed-secrets-controller created
deployment.apps/sealed-secrets-controller created
service/sealed-secrets-controller created
rolebinding.rbac.authorization.k8s.io/sealed-secrets-controller created
role.rbac.authorization.k8s.io/sealed-secrets-key-admin created
clusterrolebinding.rbac.authorization.k8s.io/sealed-secrets-controller created
clusterrole.rbac.authorization.k8s.io/secrets-unsealer created

2019/01/25 14:57:14 SealedSecrets release: v0.7.0
customresourcedefinition.apiextensions.k8s.io/sealedsecrets.bitnami.com created
serviceaccount/sealed-secrets-controller created
deployment.apps/sealed-secrets-controller created
service/sealed-secrets-controller created
rolebinding.rbac.authorization.k8s.io/sealed-secrets-controller created
role.rbac.authorization.k8s.io/sealed-secrets-key-admin created
clusterrolebinding.rbac.authorization.k8s.io/sealed-secrets-controller created
clusterrole.rbac.authorization.k8s.io/secrets-unsealer created

2019/01/25 14:57:14 
2019/01/25 14:57:14 Are SealedSecrets ready? 1/260
exec:  ./scripts/get-sealedsecretscontroller.sh
res: 
sealedsecretscontroller 0   <nil>
2019/01/25 14:57:16 Are SealedSecrets ready? 2/260
exec:  ./scripts/get-sealedsecretscontroller.sh
res: 
sealedsecretscontroller 0   <nil>
2019/01/25 14:57:18 Are SealedSecrets ready? 3/260
exec:  ./scripts/get-sealedsecretscontroller.sh
res: 
sealedsecretscontroller 0   <nil>
2019/01/25 14:57:20 Are SealedSecrets ready? 4/260
exec:  ./scripts/get-sealedsecretscontroller.sh
res: 
sealedsecretscontroller 0   <nil>
2019/01/25 14:57:22 Are SealedSecrets ready? 5/260
exec:  ./scripts/get-sealedsecretscontroller.sh
res: 
sealedsecretscontroller 0   <nil>
2019/01/25 14:57:24 Are SealedSecrets ready? 6/260
exec:  ./scripts/get-sealedsecretscontroller.sh
res: 1
sealedsecretscontroller 0 1  <nil>
exec:  ./scripts/export-sealed-secret-pubcert.sh
res: SealedSecrets release: v0.7.0
-----BEGIN CERTIFICATE-----
MIIErjCCApagAwIBAgIRANq1bsX6zBfrQSGA1Y7JBKMwDQYJKoZIhvcNAQELBQAw
ADAeFw0xOTAxMjUxOTU3MjRaFw0yOTAxMjIxOTU3MjRaMAAwggIiMA0GCSqGSIb3
DQEBAQUAA4ICDwAwggIKAoICAQC2oUtWy101dj7Wxh91e+IZ0WMDGP6NgX7xVWKr
wqcRPpEbvIhxGodCybNLJEqOi9eSu1MIX4QhzSOfnRH5c3u+Jefjpge7dOurxWW8
pptussvFS4751eIIKm9kUMi5WuwzxPHG/+qxByuNSLaRV6sRFogyZ8kuIlDhi1Ow
iU6wRhci6aZYhNQkNPrWfsO5TtQfmplY0wS+Plj/BYspuwEDMh7Dx/A5ESiDY7w9
zB7dKcLKFe4kT27VDZbhrTnGN0UjxhMx0sSkaiETFDc/IGdgFdwcSZlu9hAKe7AH
u285hxMQUvt3J7U5rpmKLsTtWOCPpjdHqkGJSm3PVI4BLqntCIiK0aln/f5/4poQ
EvVh+QK7TQfpoahMWXQYKk+MXI0XWnWLC4QcwjbmUiw1K1ickSGYQ4wxFPCuadEs
BvTuJ+JehQmretwc+kBFYA2g3nAeKa3Bp0lOkZE7LoYsOvfmpLuWfekjqrN+MCAl
roxcsEMnxYjdw8j/ulDQRAuW1uOLL9OanNB4RGlr7rBz1+/9VBZb8DsOlOaYjT14
SVrruxNC+yB6ZTBQed/jaVZ/KFrP+R+QkKDee9Ct6Q9Y/rv9iPhHFljH5C9Ve0LW
SJ9LKhpDzeFmfhV8O9wIikBe4ACnKqfb3wiuLaStplLnsqDNJF4cR2tesTGDkTRG
AnW00QIDAQABoyMwITAOBgNVHQ8BAf8EBAMCAAEwDwYDVR0TAQH/BAUwAwEB/zAN
BgkqhkiG9w0BAQsFAAOCAgEAXKjQY7PmZUUlhey9bPiHlbi9T6RQ5+a6v5ap9VWX
tBY027DJXgrjZRgKzm/oo74vh8bL6jzNfUpzHxP4wDG3V70MLkfXrOYEPva1kzZ6
4dwEz9Qu6OW4sZJmfNNKhf5BVAf6tfobRqtM6nJQAqZqNxryPebIFUOkOVW6A0hC
kkDQ+3oUsEweSGBhKJT6juLOqV8nrU+MzNOJ/XO0LzfMrOhUDTuJeTv1UjvChVeY
uvK3rt++Q+SajbOaPpW1S4HPvAcv3qM/YOvGdwWEWzAimz0bmLwglskZtj5trGY5
x9qE/ZqccLcPOe4TVCWkZD90FcFMtD/BwUC2AJUDuDpZCdcIjVpc8O4Nv0+3R38L
+BwezTym5+mGDhr3ixRj4PvTul2y3iMLa/+tSV3+n5FigMcc9ARFn7QMxmfi0twT
+rL5K49bTOryXl9yVaNnmLoopsCfLqUFlyVtjOS7WeCspwVOPQrkRudw6bq2HOy4
laDdquUkMwOhAhl2JzCSDyq9j28I3CFcjSyQpcWTWGI3CWObAqRQXtC1f0mi/rPW
Fjl0d77NK8oYzgPI7g2aOv4zE2yKaJ5Psz8nvZoof9Go8cEzf9yXILwMXC8C4GEt
Z5F6THp7WgsahZuZ1e+4adhZjUzb0Fbq5RvoxJ3s6frMHra0vHGmOFh7RO/ULnlZ
nZI=
-----END CERTIFICATE-----

secrets cert 0 SealedSecrets release: v0.7.0
-----BEGIN CERTIFICATE-----
MIIErjCCApagAwIBAgIRANq1bsX6zBfrQSGA1Y7JBKMwDQYJKoZIhvcNAQELBQAw
ADAeFw0xOTAxMjUxOTU3MjRaFw0yOTAxMjIxOTU3MjRaMAAwggIiMA0GCSqGSIb3
DQEBAQUAA4ICDwAwggIKAoICAQC2oUtWy101dj7Wxh91e+IZ0WMDGP6NgX7xVWKr
wqcRPpEbvIhxGodCybNLJEqOi9eSu1MIX4QhzSOfnRH5c3u+Jefjpge7dOurxWW8
pptussvFS4751eIIKm9kUMi5WuwzxPHG/+qxByuNSLaRV6sRFogyZ8kuIlDhi1Ow
iU6wRhci6aZYhNQkNPrWfsO5TtQfmplY0wS+Plj/BYspuwEDMh7Dx/A5ESiDY7w9
zB7dKcLKFe4kT27VDZbhrTnGN0UjxhMx0sSkaiETFDc/IGdgFdwcSZlu9hAKe7AH
u285hxMQUvt3J7U5rpmKLsTtWOCPpjdHqkGJSm3PVI4BLqntCIiK0aln/f5/4poQ
EvVh+QK7TQfpoahMWXQYKk+MXI0XWnWLC4QcwjbmUiw1K1ickSGYQ4wxFPCuadEs
BvTuJ+JehQmretwc+kBFYA2g3nAeKa3Bp0lOkZE7LoYsOvfmpLuWfekjqrN+MCAl
roxcsEMnxYjdw8j/ulDQRAuW1uOLL9OanNB4RGlr7rBz1+/9VBZb8DsOlOaYjT14
SVrruxNC+yB6ZTBQed/jaVZ/KFrP+R+QkKDee9Ct6Q9Y/rv9iPhHFljH5C9Ve0LW
SJ9LKhpDzeFmfhV8O9wIikBe4ACnKqfb3wiuLaStplLnsqDNJF4cR2tesTGDkTRG
AnW00QIDAQABoyMwITAOBgNVHQ8BAf8EBAMCAAEwDwYDVR0TAQH/BAUwAwEB/zAN
BgkqhkiG9w0BAQsFAAOCAgEAXKjQY7PmZUUlhey9bPiHlbi9T6RQ5+a6v5ap9VWX
tBY027DJXgrjZRgKzm/oo74vh8bL6jzNfUpzHxP4wDG3V70MLkfXrOYEPva1kzZ6
4dwEz9Qu6OW4sZJmfNNKhf5BVAf6tfobRqtM6nJQAqZqNxryPebIFUOkOVW6A0hC
kkDQ+3oUsEweSGBhKJT6juLOqV8nrU+MzNOJ/XO0LzfMrOhUDTuJeTv1UjvChVeY
uvK3rt++Q+SajbOaPpW1S4HPvAcv3qM/YOvGdwWEWzAimz0bmLwglskZtj5trGY5
x9qE/ZqccLcPOe4TVCWkZD90FcFMtD/BwUC2AJUDuDpZCdcIjVpc8O4Nv0+3R38L
+BwezTym5+mGDhr3ixRj4PvTul2y3iMLa/+tSV3+n5FigMcc9ARFn7QMxmfi0twT
+rL5K49bTOryXl9yVaNnmLoopsCfLqUFlyVtjOS7WeCspwVOPQrkRudw6bq2HOy4
laDdquUkMwOhAhl2JzCSDyq9j28I3CFcjSyQpcWTWGI3CWObAqRQXtC1f0mi/rPW
Fjl0d77NK8oYzgPI7g2aOv4zE2yKaJ5Psz8nvZoof9Go8cEzf9yXILwMXC8C4GEt
Z5F6THp7WgsahZuZ1e+4adhZjUzb0Fbq5RvoxJ3s6frMHra0vHGmOFh7RO/ULnlZ
nZI=
-----END CERTIFICATE-----
  <nil>
exec:  ./scripts/clone-cloud-components.sh
res: 
{ Cloning into './tmp/openfaas-cloud'...
 0}
exec:  ./scripts/deploy-cloud-components.sh
res: deployment.apps/of-builder created
service/of-builder created
clusterrole.rbac.authorization.k8s.io/sealed-secrets-manager created
rolebinding.rbac.authorization.k8s.io/manage-sealed-secrets created
deployment.apps/of-router created
service/of-router created
service/auth created
Creating payload-secret in openfaas-fn
secret/payload-secret created
Fetch templates from repository: https://github.com/openfaas/templates.git at master
Forwarding from 127.0.0.1:31111 -> 8080
Forwarding from [::1]:31111 -> 8080
Checking if OpenFaaS GW is up.
Handling connection for 31111
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=utf-8
Location: /ui/
Date: Fri, 25 Jan 2019 19:57:43 GMT
Content-Length: 39

<a href="/ui/">Moved Permanently</a>.

Calling the OpenFaaS server to validate the credentials...
Handling connection for 31111
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
credentials saved for admin http://127.0.0.1:31111
Deploying: import-secrets.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/import-secrets

Deploying: system-github-event.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/system-github-event

Deploying: github-push.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/github-push

Deploying: git-tar.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/git-tar

Deploying: buildshiprun.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/buildshiprun

Deploying: garbage-collect.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/garbage-collect

Deploying: github-status.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/github-status

Deploying: pipeline-log.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/pipeline-log

Deploying: list-functions.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/list-functions

Deploying: audit-event.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/audit-event

Deploying: echo.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/echo

Deploying: system-metrics.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/system-metrics

Fetch templates from repository: https://github.com/openfaas-incubator/node8-express-template at master
Deploying: system-dashboard.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/system-dashboard

Deploying: system-list-functions.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/system-list-functions

{deployment.apps/of-builder created
service/of-builder created
clusterrole.rbac.authorization.k8s.io/sealed-secrets-manager created
rolebinding.rbac.authorization.k8s.io/manage-sealed-secrets created
deployment.apps/of-router created
service/of-router created
service/auth created
Creating payload-secret in openfaas-fn
secret/payload-secret created
Fetch templates from repository: https://github.com/openfaas/templates.git at master
Forwarding from 127.0.0.1:31111 -> 8080
Forwarding from [::1]:31111 -> 8080
Checking if OpenFaaS GW is up.
Handling connection for 31111
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=utf-8
Location: /ui/
Date: Fri, 25 Jan 2019 19:57:43 GMT
Content-Length: 39

<a href="/ui/">Moved Permanently</a>.

Calling the OpenFaaS server to validate the credentials...
Handling connection for 31111
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
credentials saved for admin http://127.0.0.1:31111
Deploying: import-secrets.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/import-secrets

Deploying: system-github-event.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/system-github-event

Deploying: github-push.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/github-push

Deploying: git-tar.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/git-tar

Deploying: buildshiprun.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/buildshiprun

Deploying: garbage-collect.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/garbage-collect

Deploying: github-status.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/github-status

Deploying: pipeline-log.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/pipeline-log

Deploying: list-functions.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/list-functions

Deploying: audit-event.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/audit-event

Deploying: echo.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/echo

Deploying: system-metrics.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/system-metrics

Fetch templates from repository: https://github.com/openfaas-incubator/node8-express-template at master
Deploying: system-dashboard.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/system-dashboard

Deploying: system-list-functions.
Handling connection for 31111
Handling connection for 31111

Deployed. 202 Accepted.
URL: http://127.0.0.1:31111/function/system-list-functions

 cp: ./tmp/generated-of-auth-dep.yml: No such file or directory
2019/01/25 14:57:41 Attempting to expand templates from https://github.com/openfaas/templates.git
2019/01/25 14:57:41 Fetched 15 template(s) : [csharp csharp-armhf dockerfile go go-armhf java8 node node-arm64 node-armhf php7 python python-armhf python3 python3-armhf ruby] from https://github.com/openfaas/templates.git
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    39  100    39    0     0   1278      0 --:--:-- --:--:-- --:--:--  1300
2019/01/25 14:57:51 Attempting to expand templates from https://github.com/openfaas-incubator/node8-express-template
2019/01/25 14:57:51 Fetched 2 template(s) : [node8-express node8-express-armhf] from https://github.com/openfaas-incubator/node8-express-template
 0}
Plan completed in 68.837006 seconds

## Steps to Reproduce (for bugs)
Just follow the steps in this instructions.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
   0.8.3 

* Docker version `docker version` (e.g. Docker 17.0.05 ):
   Docker 18.09.1

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
   Kubernetes (FaaS-netes)

* Operating System and version (e.g. Linux, Windows, MacOS):
  MacOS

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Thank you for trying the tool 

What error did you get?

We usually run reset.sh between running the tool too.

**Comment by alexellis** [comment]
> 2019/01/25 14:57:00 Error: failed to download "stable/nginx-ingress" (hint: running helm repo update may help)

I can see this error ^ what country do you live in? Some governments block access to CDNs.

Alex

**Comment by M-nana** [comment]
I live in the United States. The error is 
cp: ./tmp/generated-of-auth-dep.yml: No such file or directory

**Comment by alexellis** [comment]
Did you run the reset.sh that I requested?

**Comment by alexellis** [comment]
What do you want to use for your HTTPS certificates and DNS? You can pick AWS Route53 or DNS or Google Cloud DNS

I just ran the whole setup with Google Cloud DNS on a DigitalOcean cluster and received no errors.

If I do get errors during development or need to change configuration I just run `contrib/reset.sh` and execute the process again.

**Comment by alexellis** [comment]
@ivanayov please could you review this issue when you come in on Monday? I don't have Route53 configured to verify this scenario.

**Comment by ivanayov** [comment]
I know what the error comes from. It's after an update not to generate template for of-auth, when disabled. I will commit fix shortly

**Comment by ivanayov** [comment]
Derek set title: Non-generated template referenced when auth is disabled

**Comment by alexellis** [comment]
@M-nana please try again, and I've said it a few times already, but use the ./reset.sh script first, or use ofc-bootstrap on a fresh cluster and then let us know how you get on.

Ivana thanks for fixing. :)

**Comment by M-nana** [comment]
I will try it! Thank you guys!
