### ISSUE TITLE
Offer to install IngressController with HostPort

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ofc-bootstrap#62]
## Expected Behaviour

We should offer to install IngressController with HostPort for Kubernetes running on bare metal, or where an LB is not available. This could also reduce the cost for testing clusters by removing the need for an LB.

This would also enable the use-case with "k3s" from @ibuildthecloud

## Possible Solution

See the Nginx helm chart on configuring a HostPort / Host networking so that the ingress controller binds to port 80/443 from the container.

**Comment by affix** [comment]
:+1:

**Comment by alexellis** [comment]
@affix fixed and available
