### ISSUE TITLE
Tiller error in windows

### ISSUE THREAD

**Issue by zeerorg** [openfaas-incubator/ofc-bootstrap#64]
Getting an error when running ofc-bootstrap on windows in git bash.

## Expected Behaviour
The script shouldn't give an error and continue.

## Steps to Reproduce (for bugs)
Run ofc-bootstrap in windows under git bash.

## Context
Trying to setup openfaas cloud from windows dev machine.

## Your Environment

* FaaS-CLI version 0.8.1:

* Docker version 18.09.1:

* Kubernetes?

* Windows:

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

Error log:
![image](https://user-images.githubusercontent.com/13547997/52165891-8bdbe880-272c-11e9-8117-3ab10bfcb968.png)

The kubernetes cluster was hosted on DigitalOcean

**Comment by zeerorg** [comment]
I'll give it a try, totally forgot about that.

**Comment by alexellis** [comment]
I've not tested outside of Mac/Linux. Could you include the complete output please? WSL sounds like a great option too.

**Comment by zeerorg** [comment]
The output just continues on like this. with the tiller error. And continues to retry till 260 times.

**Comment by alexellis** [comment]
ln -s /bin/sh /bin/bash ? Would that help?

**Comment by alexellis** [comment]
Failing that run it in a Linux Docker image or VM on DO.

**Comment by zeerorg** [comment]
I think we should close this issue, and specify wsl on windows in docs
