### ISSUE TITLE
Template requires do-access-token

### ISSUE THREAD

**Issue by burf2000** [openfaas-incubator/ofc-bootstrap#67]
./ofc-bootstrap -yaml=init.yaml with TLS to false still errors because do-access-token is missing

## Expected Behaviour
I believe with TLS off, it should not need do-access-token

## Current Behaviour
CLI:
 commit:  a141dedf94ffeed84412365fd591bdc8999c5a1b
 version: 0.8.3

panic: stat /home/burf2000/Downloads/do-access-token: no such file or directory

goroutine 1 [running]:
main.main()
	/home/burf2000/work/src/github.com/openfaas-incubator/ofc-bootstrap/main.go:114 +0x8e3

## Possible Solution
I guess use DO?

## Steps to Reproduce (for bugs)
./ofc-bootstrap -yaml=init.yaml

## Your Environment
Ubuntu 16.04

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by zeerorg** [comment]
Can you provide logs ?
