### ISSUE TITLE
ofc-bootstrap failed to install cert-manager

### ISSUE THREAD

**Issue by tsahi-duek** [openfaas-incubator/ofc-bootstrap#79]
When deploying OFC on EKS, cert-manager-webhook pod ends in a CrashLoopBackOff
## Expected Behaviour
cert-manager-webhook Pod should be in Running state

## Current Behaviour
cert-manager-webhook Pod ends in CrashLoopBackOff state

## Possible Solution
There is an issue with API aggregation certificates on EKS (see https://github.com/jetstack/cert-manager/issues/1220 and https://github.com/aws/containers-roadmap/issues/152).
A possible solution is to use helm chart v0.6.6 (which use v0.6.2 of cert-manager)

## Steps to Reproduce (for bugs)
1. Launch an EKS cluster
2. Configure OFC init.yml and run ./ofc-bootstrap

## Context
The process of ofc-bootstrap didn't complete successfully.

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  a141dedf94ffeed84412365fd591bdc8999c5a1b
 version: 0.8.3
* Docker version `docker version` (e.g. Docker 17.0.05 ):
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:        Tue Nov 14 22:03:51 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   402dd4a/17.06.2-ce
 Built:        Tue Nov 14 22:04:39 2017
 OS/Arch:      linux/amd64
 Experimental: false
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-12-06T01:33:57Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
* Operating System and version (e.g. Linux, Windows, MacOS):
Amazon Linux 2
* Link to your project or a code example to reproduce issue:
Just run ofc-bootstrap to provision OFC over EKS

**Comment by alexellis** [comment]
Hi thank you for raising this issue. Would you like to work on the fix?

Alex

**Comment by alexellis** [comment]
I've fixed this issue, thank you for reporting it. 👍
