### ISSUE TITLE
basic_auth removal + secrets filters break deployment

### ISSUE THREAD

**Issue by mbarlow** [openfaas-incubator/ofc-bootstrap#85]
## Expected Behaviour

Cloning the project, copying example.init.yaml to init.yaml (modify config options for TLS, Oauth, github app, etc), and running ./ofc-bootstrap should deploy to cluster the full installation without errors.

## Current Behaviour

During the installation w/ the current master, the ./scripts/deploy-cloud-components.sh will fail on missing basic-auth secret. Kubectl port forward will fail, the logic for "Checking if OpenFaas GW is up" will fail, etc.

## Possible Solution

Add basic_auth=true back into example.init.yaml, modify filters for secrets to set basic_auth to default, add BasicAuth bool back into pkg/types/types.go Plan struct.

## Steps to Reproduce (for bugs)

1. create a clean local env
2. create a new kubernetes cluster
3. clone the project
4. attempt to run ./ofc-bootstrap with your modified init.yaml file

## Context

Cannot access the openfaas-cloud install, missing github functions, clusterissuer deployments also fail and need to be manually applied.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.8.3

* Docker version `docker version` (e.g. Docker 17.0.05 ): 18.09.2

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS Mojave

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Please use an older version prior to the change from @mdekov. 

Alex

**Comment by mbarlow** [comment]
No problem, I have it working locally now with the modifications I suggested. Just letting you know there is an issue atm

**Comment by alexellis** [comment]
Well I'm a bit confused because the guys tested their changes before having them merged. I using the latest release or are you building fresh from master?

**Comment by alexellis** [comment]
--
Join Slack to connect with the community
https://docs.openfaas.com

**Comment by mbarlow** [comment]
sorry, I'm building fresh from master

**Comment by viveksyngh** [comment]
@mbarlow 

Can you please retry but adding a feature list to `init.yaml`. This enables those features and creates secret required for those features.

```yaml
features:
  - basic_auth
  - auth 
  - scm_github
 ```

**Comment by alexellis** [comment]
@viveksyngh - there is no `features` list in `init.yaml`. The features are derived from what is enabled/turned on. FYI basic_auth for the gateway _must never be disabled_ and this is an unsupported scenario.

I've moved the filter to `default` however. Can you confirm whether this resolves the issue?

**Comment by martindekov** [comment]
Hello @mbarlow I apolagize for the confusion, had my own `init.yml` with which I tested and possibly forgot to add the changes to the example one. Changin the In general if you want secret created/is mandatoy apply `default` filter. Otherwise the `scm-github` -> `scm_github` is fixed in [this PR](https://github.com/openfaas-incubator/ofc-bootstrap/pull/84) but forgot it is a breaking change.
