### ISSUE TITLE
Just an Idea:  Kong to replace the NGINX controller

### ISSUE THREAD

**Issue by rjpalermo1** [openfaas-incubator/ofc-bootstrap#91]
Proposed idea:  Optionally replace the NGINX Ingress with NGINX-based Kong controller.

## Expected Behaviour

Use Kong as the K8 ingress controller to realize the benefits of an API gateway protecting the OpenFaas endpoints.  Not many people want their functions exposed to the public Internet and additionally not all want to have a seperate https URL for each endoint.  Would be great to have Kong direct and protect traffic to a function from a single https://api.server.com/function or even several https://function.api.server.com/ endpoints.

## Possible Solution

https://github.com/luispabon/kong-certbot-agent provided an LE manager for Kong.

## Context

Secure API Gateway protected functions.

## Your Environment

Kubernetes, minikube, Mac OS, Postgres, OpenFaas, Kong local dev setup for goal of a vendor-neutral portable cloud platform

**Comment by alexellis** [comment]
Derek add label: wontfix

**Comment by alexellis** [comment]
You're welcome to deploy OpenFaaS Cloud manually and make use of whatever ingress controller you prefer.

https://github.com/openfaas/openfaas-cloud

Alex

**Comment by rjpalermo1** [comment]
ok thanks.  I will figure it out.

appreciate your wizardry here Alex.
