### ISSUE TITLE
Add feature flag for Dockerfile template

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ofc-bootstrap#94]
## Expected Behaviour

Support for lang: dockerfile should be configurable as per - https://github.com/openfaas/openfaas-cloud/pull/422

## Current Behaviour

Off by default

## Possible Solution

Expose the configuration option in the init.yaml file and then read it and template the configuration accordingly.

## Steps to Reproduce (for bugs)

When fixed you can do:

1.  Enable dockerfile type in init.yaml
2. Deploy
3. faas-cli new --lang dockerfile tester
4. git push and see the above deployed as an endpoint

**Comment by sterchelen** [comment]
I take it !

**Comment by alexellis** [comment]
How long do you think it will take you to do this task?

**Comment by sterchelen** [comment]
Just create a working environment for the openfaas's projects... I would
say for Wednesday.

Is it urgent?

**Comment by matipan** [comment]
@sterchelen I already did some work, if you want we can chat a bit in openfaas's slack about this 👍

**Comment by sterchelen** [comment]
Yep Matias!
