### ISSUE TITLE
Feature: add config option for scale to zero (enable faasIdler)

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ofc-bootstrap#97]
## Expected Behaviour

The user should set a new flag in init.yaml called `scale_to_zero` or similar.

https://github.com/openfaas/faas-netes/tree/master/chart/openfaas#configuration

## Current Behaviour

Users can update this manually.

## Possible Solution

This should be passed through to https://github.com/openfaas-incubator/ofc-bootstrap/blob/master/scripts/install-openfaas.sh#L6 where it can be passed into the `faasIdler.dryRun` flag of the helm chart.

If `scale_to_zero` is enabled, then `dryRun` takes the inverse i.e. `false`.

Add `scale_to_zero` as `false` in init.yaml.

## Steps to Reproduce (for bugs)

When complete here's the acceptance criteria:

1.  User can set `scale_from_zero: true` in init.yaml
2. `kubectl describe faas-idler -n openfaas` shows dryRun is set to `false`.
3. User then sets `scale_from_zero: false` in init.yaml OR comments out the line
4. `kubectl describe faas-idler -n openfaas` shows dryRun is set to `true`.

## Context

This could add efficiency savings to OpenFaaS Cloud operators

**Comment by alexellis** [comment]
Similar closed / completed PR: https://github.com/openfaas-incubator/ofc-bootstrap/pull/95

**Comment by matipan** [comment]
I can pick this up 👍

**Comment by matipan** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Thanks @matipan

**Comment by matipan** [comment]
I completely forgot about this. I'm starting it now :+1:
