### ISSUE TITLE
Error with gateway_config.yml template

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ofc-bootstrap#99]
## Current Behaviour

```
2019/04/09 22:12:44 template: templates/gateway_config.yml:38:28: executing "templates/gateway_config.yml" at <.EnableDockerfileLan...>: can't evaluate field EnableDockerfileLang in type stack.gatewayConfig
```
This happened on Linux with `enable_dockerfile_lang: true` in `init.yaml`

I also had the following errors after that:

```

 cp: cannot stat './tmp/generated-gateway_config.yml': No such file or directory
cp: cannot stat './tmp/generated-github.yml': No such file or directory
cp: cannot stat './tmp/generated-slack.yml': No such file or directory
cp: cannot stat './tmp/generated-dashboard_config.yml': No such file or directory
cp: cannot stat './tmp/generated-of-auth-dep.yml': No such file or directory
2019/04/09 22:13:13 Attempting to expand templates from https://github.com/openfaas/templates.git
2019/04/09 22:13:15 Fetched 15 template(s) : [csharp csharp-armhf dockerfile go go-armhf java8 node node-arm64 node-armhf php7 python python-armhf python3 python3-armhf ruby] from https://github.com/openfaas/templates.git
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    39  100    39    0     0    105      0 --:--:-- --:--:-- --:--:--   105
cp: cannot stat '../generated-stack.yml': No such file or directory
```

I assume these are related due to the issue stopping the template flow.

**Comment by alexellis** [comment]
@matipan @zeerorg please could you take a look?

**Comment by alexellis** [comment]
I used https://github.com/openfaas-incubator/ofc-bootstrap/tree/0.5.7 - but updating to a build from master may resolve the issue.

**Comment by matipan** [comment]
I see that 0.5.7 does not have the gatewayConfig struct updated with the `EnableDockerfileLang` field: https://github.com/openfaas-incubator/ofc-bootstrap/blob/0.5.7/pkg/stack/stack.go

I'm about to install ofc on GKE using ofc-bootstrap master. I'll let you know how it goes

**Comment by matipan** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Thank you. The 0.6.0 binary is available now

**Comment by matipan** [comment]
@alexellis I just deployed an ofc cluster using 0.6.0. It worked great with both dockerfile support and custom templates 🎉 

> 2019/04/09 22:12:44 template: templates/gateway_config.yml:38:28: executing "templates/gateway_config.yml" at <.EnableDockerfileLan...>: can't evaluate field EnableDockerfileLang in type stack.gatewayConfig

I believe this error message was expected since the template had a field that the struct did not.

Do you want to try again with 0.6.0 or should we close?

**Comment by alexellis** [comment]
I've tried it with the new release today and I was unable to reproduce the error.

This makes things a little complicated - we have a chicken & egg problem when merging patches to the example.init.yaml and cutting a new release.

For the time the yaml file is changed, the latest binary release will crash if a user pulls it down before someone kicks off a release build and Travis completes that.
